name: Example Workflow

on:
    push:
        branches:
            - features-0001-ruiz

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Decir hola
              run: echo "Hola, mundo!"

            - name: Decir adios
              run: echo "adios"

      